
version: "3.8"
services:
  mongo_compose:
    container_name: mongo_compose
    image: mongo
    restart: always
    ports:
      - "27017:27017"
    volumes:
      - db-compose-data:/data/db

  mexpress_compose:
    container_name: mexpress_compose
    image: mongo-express
    restart: always
    ports:
      - "8081:8081"
    env_file: .env
    depends_on: 
      - mongo_compose

  go_compose:
    container_name: go_compose
    build:
      context: ./
      dockerfile: Dockerfile_pop
    depends_on: 
      - mongo_compose

  go_api_compose:
    container_name: go_api_compose
    build:
      context: ./
      dockerfile: Dockerfile_api
    ports:
      - "7777:7777"
    depends_on: 
      - mongo_compose
    

volumes:
  db-compose-data:

